#! /usr/bin/env python
import argparse
from pathlib import Path
from lua_bundler import bundle

parser = argparse.ArgumentParser(
    prog = 'LUABundle',
    description='Bundle LUA Scripts for ArduPilot'
)

parser.add_argument('source', nargs='?', default=None, type=Path)
parser.add_argument('target', nargs='?', default=None, type=Path)
parser.add_argument('-w', '--workdir', required=False, type=Path)

args = parser.parse_args()

if not args.source or not args.target:
    parser.print_help()
    exit()

bundle(
    args.source, 
    args.target, 
    args.workdir
)